/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const AUTH_BASE_URL: typeof import('@arco-design/web-vue')['UTH_BASE_URL']
}
